import{a as i,S as l}from"./assets/vendor-65b0d63f.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerpolicy&&(n.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?n.credentials="include":t.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();i.defaults.headers.common["x-api-key"]="live_YGiFEHjPi1lBCUuzNbWelyd7J1oPEfn9W20OXOYFFrZcwqF6HuW05CNOxCFEtTY7";async function d(){return await i.get("https://api.thecatapi.com/v1/breeds").then(e=>e.data)}async function u(e){return await i.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`).then(r=>r.data)}const s={breedSelect:document.querySelector(".js-breed-select"),catInfo:document.querySelector(".cat-info")},f=new l({select:s.breedSelect});async function m(){try{const e=s.breedSelect.value,r=await u(e);p(r)}catch(e){console.log(e)}}function p(e){const r=e[0].url,o=e[0].breeds[0],c=`<div class="wrapper">
      <img class="img" src="${r}" alt="${o.name}"/>
      <div class="info">
        <h2 class="name">${o.name}</h2>
        <p><b class="description">Description:</b> ${o.description}</p>
        <p><b class="temperament">Temperament:</b> ${o.temperament}</p>   
       </div>
    </div>`;s.catInfo.insertAdjacentHTML("afterbegin",c)}async function h(){try{await d().then(e=>{const r=e.map(({id:o,name:c})=>({value:o,text:c}));console.log(r),f.setData(Array.from(r))}),s.breedSelect.addEventListener("change",m)}catch(e){console.log(e)}}h();
//# sourceMappingURL=commonHelpers.js.map
