import{a as l,S as u,i as d}from"./assets/vendor-33682a3e.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();l.defaults.headers.common["x-api-key"]="live_YGiFEHjPi1lBCUuzNbWelyd7J1oPEfn9W20OXOYFFrZcwqF6HuW05CNOxCFEtTY7";async function m(){return await l.get("https://api.thecatapi.com/v1/breeds").then(e=>e.data)}async function f(e){return await l.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`).then(a=>a.data)}const n={breedSelect:document.querySelector(".js-breed-select"),catInfo:document.querySelector(".cat-info"),loader:document.querySelector(".loader"),title:document.querySelector(".animate__animated")};function s(e,a){e.classList.toggle("hidden",!a)}n.title.classList.add("animate__animated","animate__zoomInDown");n.title.addEventListener("animationend",()=>{y()});s(n.breedSelect,!1);s(n.loader,!0);const p=new u({select:n.breedSelect});async function h(){try{s(n.loader,!0),s(n.catInfo,!1);const e=n.breedSelect.value,a=await f(e);g(a)}catch{d.show({position:"topRight",message:"Oops! Something went wrong! Try reloading the page!"})}s(n.loader,!1)}function g(e){const a=e[0].url,r=e[0].breeds[0],i=`<div class="card">
  <img class="img" src="${a}" alt="${r.name}"/>
      <div class="info">
        <h2 class="name">${r.name}</h2>
        <p><span class="description">Description: </span> ${r.description}</p>
        <p><span class="temperament">Temperament: </span> ${r.temperament}</p>   
       </div>
</div>`;n.catInfo.innerHTML=i,s(n.catInfo,!0)}async function y(){try{await m().then(e=>{const a=e.map(({id:r,name:i})=>({value:r,text:i}));console.log(a),p.setData(Array.from(a))}),s(n.breedSelect,!0),n.breedSelect.addEventListener("change",h)}catch{d.show({position:"topRight",message:"Oops! Something went wrong! Try reloading the page!"})}s(n.loader,!1)}
//# sourceMappingURL=commonHelpers.js.map
